module.exports = [
  {
    slug: 'access-control',
    output: 'accessControl.html',
    number: '01',
    name: 'access control',
    eyebrow: 'The access layer',
    title: 'Control the',
    titleAccent: 'threshold.',
    heroTitle: 'Entry,',
    heroAccent: 'by design.',
    heroDescription: 'Give the right people the right access, with a clear record of every opening, change, and exception.',
    intro: 'A modern access system turns doors and gates into useful, manageable parts of your operation. We design around how your people actually move.',
    bandKicker: 'Built around your site',
    bandTitle: 'From first scan',
    bandAccent: 'to final exit.',
    bandIndex: 'Designed / installed / supported',
    ctaKicker: 'A better way in',
    ctaTitle: 'Make every',
    ctaAccent: 'entry count.',
    ctaCopy: 'Tell us about your doors, gates, and team. We’ll help you find the right access strategy.',
    ctaButton: 'Plan your system',
    features: [
      ['Credentials that fit', 'Cards, mobile credentials, keypads, and readers matched to each opening and user group.'],
      ['Rules with context', 'Set schedules, zones, and permissions that adapt as teams, tenants, and needs change.'],
      ['Useful visibility', 'See who entered, when they entered, and where unusual activity needs a closer look.'],
      ['Ready for growth', 'Start with the doors that matter now and extend the system as your site evolves.'],
    ],
    process: [
      ['Map the movement', 'We look at doors, people, schedules, and sensitive areas before recommending hardware.'],
      ['Make access simple', 'Clear permissions and intuitive credentials help your team move without friction.'],
      ['Keep it current', 'Ongoing support keeps permissions accurate when people, spaces, and priorities change.'],
    ],
  },
  {
    slug: 'alarm-systems',
    output: 'alarmSystems.html',
    number: '02',
    name: 'alarm systems',
    eyebrow: 'The response layer',
    title: 'Less noise.',
    titleAccent: 'More clarity.',
    heroTitle: 'Signal,',
    heroAccent: 'with purpose.',
    heroDescription: 'Detect the unexpected early, then give the right people a clear next action when it matters most.',
    intro: 'The best alarm system is specific to your risks and easy to act on. We connect detection, communication, and response into one dependable plan.',
    bandKicker: 'When something changes',
    bandTitle: 'Know what',
    bandAccent: 'happens next.',
    bandIndex: 'Detect / verify / respond',
    ctaKicker: 'A calmer response',
    ctaTitle: 'Make the',
    ctaAccent: 'signal useful.',
    ctaCopy: 'Share the risks you are planning around. We’ll help shape an alarm system that fits your site.',
    ctaButton: 'Talk through your risks',
    features: [
      ['Early detection', 'Cover the signals that matter, from intrusion and forced entry to environmental risks.'],
      ['Clear escalation', 'Route alerts to the right people with the information they need to make a decision.'],
      ['Professional monitoring', 'Add a trained response layer that stays attentive when your team cannot.'],
      ['Fewer false alarms', 'Thoughtful placement, configuration, and user guidance help keep urgency meaningful.'],
    ],
    process: [
      ['Detect the signal', 'Sensors watch the points and conditions that matter to your building and operation.'],
      ['Understand the event', 'Clear alerts and sensible zones help separate a real concern from a routine moment.'],
      ['Move with confidence', 'Your team and monitoring partners have a defined path from alert to resolution.'],
    ],
  },
  {
    slug: 'video-surveillance',
    output: 'videoSurveillance.html',
    number: '03',
    name: 'video surveillance',
    eyebrow: 'The visibility layer',
    title: 'More than',
    titleAccent: 'a picture.',
    heroTitle: 'See what',
    heroAccent: 'matters.',
    heroDescription: 'Turn cameras into useful awareness with coverage, analytics, and footage your team can act on.',
    intro: 'A thoughtful camera system helps you see the whole story, whether you are checking a live event, reviewing a detail, or improving how a space works.',
    bandKicker: 'From live view to insight',
    bandTitle: 'Watch less.',
    bandAccent: 'Understand more.',
    bandIndex: 'Observe / analyze / review',
    ctaKicker: 'A clearer point of view',
    ctaTitle: 'Put your',
    ctaAccent: 'eyes on it.',
    ctaCopy: 'Tell us what you need to see and where the blind spots are. We’ll help build a practical camera plan.',
    ctaButton: 'Plan your coverage',
    features: [
      ['Coverage that works', 'Plan views, lighting, storage, and camera placement around the moments you need to understand.'],
      ['Analytics with intent', 'Use smart detection to surface activity instead of asking your team to watch everything.'],
      ['Fast review', 'Find the relevant time, person, vehicle, or event without losing hours to manual searching.'],
      ['Useful anywhere', 'Give authorized people secure access to the view they need, on site or away from it.'],
    ],
    process: [
      ['Frame the right view', 'We identify the entrances, work areas, edges, and details where visibility creates value.'],
      ['Prioritize the event', 'Analytics and alerts help your team focus on activity that deserves attention now.'],
      ['Learn from the record', 'Searchable footage supports investigations, accountability, and better daily decisions.'],
    ],
  },
  {
    slug: 'energy-management',
    output: 'energyManagement.html',
    number: '04',
    name: 'energy management',
    eyebrow: 'The efficiency layer',
    title: 'Comfort that',
    titleAccent: 'works smarter.',
    heroTitle: 'Use less,',
    heroAccent: 'live well.',
    heroDescription: 'Manage temperature, lighting, and energy from anywhere with a connected system built around your home.',
    intro: 'A home energy management system gives you a clearer view of what your household uses and the control to make comfort more efficient.',
    bandKicker: 'Small changes, visible impact',
    bandTitle: 'Make every',
    bandAccent: 'watt count.',
    bandIndex: 'Control / schedule / save',
    ctaKicker: 'Ready for a more efficient home?',
    ctaTitle: 'Bring your home',
    ctaAccent: 'back under control.',
    ctaCopy: 'Call Lloyd Security for a free consultation about home energy management systems and saving money on energy.',
    ctaButton: 'Start a conversation',
    features: [
      ['Remote thermostat control', 'Adjust heating and cooling from your smartphone, tablet, or laptop before you arrive home.'],
      ['Smarter lighting', 'Turn lights on or off remotely and use location-based rules to avoid waste.'],
      ['Comfort on schedule', 'Pre-set temperature routines that fit your household and your daily schedule.'],
      ['One connected experience', 'Use the Alarm.com app to bring home automation and energy decisions together.'],
    ],
    process: [
      ['Set your preferences', 'Choose the temperatures, lighting scenes, and routines that match the way your household moves.'],
      ['Control from anywhere', 'Use the Alarm.com app to make an adjustment from the couch, the office, or the road.'],
      ['Let the system work', 'Automated rules keep comfort consistent while helping reduce unnecessary energy use.'],
    ],
  },
]